[env:esp32dev]
platform = espressif32
board = esp32dev  ; Good for standard ESP32
framework = arduino

upload_speed = 115200
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    https://github.com/lovyan03/LovyanGFX.git
    https://github.com/Bodmer/TJpg_Decoder.git
    bblanchon/ArduinoJson@^6.21.5

board_upload.erase_flash = true
