[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 115200
board_build.flash_mode = dio

; Ports auto-detect on Windows (COMx). Uncomment + set if detection fails:
; upload_port = COM3
; monitor_port = COM3

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    bodmer/TJpg_Decoder @ ^1.1.0
    bblanchon/ArduinoJson @ ^6.21.5
